import Link from "next/link";
import "../public.css";

const LAST_UPDATED = "September 28, 2026";
const CONTACT_EMAIL = "qninying@quinaillc.com";

export default function TermsPage() {
  return (
    <main className="hp-shell">
      <div className="hp-content-narrow">
        <p>
          <Link href="/" className="hp-back-link">
            &larr; Back to HosPulse
          </Link>
        </p>
        <h1>Terms of Service</h1>
        <p>Last updated: {LAST_UPDATED}</p>

        <p>
          HosPulse is operated by Quinai LLC (&quot;HosPulse,&quot; &quot;we,&quot; &quot;us&quot;).
          By using the HosPulse dashboard, you agree to these terms. The free public Health
          Snapshot requires no account and no agreement to use.
        </p>

        <h2>What HosPulse is</h2>
        <p>
          HosPulse is a hospital financial monitoring tool for rural and Critical Access
          hospital management companies. It computes financial trend metrics from public CMS
          cost report data and, for companies with an account, from monthly exports the
          company itself uploads, and it generates AI-assisted briefings and findings from
          those already-computed numbers.
        </p>

        <h2>Who can use the dashboard</h2>
        <p>
          The dashboard is for staff authorized by a hospital management company that has an
          account with HosPulse. You are responsible for keeping your sign-in link and any
          device you use to access it secure, and for the accuracy of anything you upload on
          your company&apos;s behalf.
        </p>

        <h2>What you upload</h2>
        <p>
          HosPulse is not built to receive patient health information. Every file you upload
          is automatically screened, and any file that appears to contain patient names,
          birth dates, or medical record numbers is rejected before it is stored. Do not
          attempt to upload patient health information, and do not attempt to access data
          belonging to a hospital management company other than your own.
        </p>

        <h2>AI-generated briefings and findings</h2>
        <p>
          Briefings and cost-report findings are generated by an AI model from your
          company&apos;s own computed metrics, and every figure in them is checked against
          that underlying data before it is shown to you &mdash; HosPulse rejects any
          AI-generated output containing a number not present in the source data. Even so,
          this content is a starting point for your own review, not a substitute for your own
          financial or clinical judgment. You are responsible for decisions you make based on
          it.
        </p>

        <h2>The service is provided as-is</h2>
        <p>
          HosPulse is an early-stage product. It is provided &quot;as is,&quot; without
          warranty of any kind, express or implied. We do not guarantee the service will be
          uninterrupted, error-free, or available at all times.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the fullest extent permitted by law, Quinai LLC is not liable for any indirect,
          incidental, or consequential damages arising from your use of HosPulse, including
          decisions made in reliance on its briefings or findings.
        </p>

        <h2>Your data</h2>
        <p>
          Data you or your company upload remains yours. HosPulse does not sell it and does
          not claim ownership of it. See the{" "}
          <Link href="/privacy">Privacy Policy</Link> for what we collect and how it is used.
        </p>

        <h2>Ending access</h2>
        <p>
          We may suspend or end a company&apos;s access to the dashboard, including for
          misuse of the service or an attempt to access another company&apos;s data. You may
          stop using the dashboard at any time.
        </p>

        <h2>Changes to these terms</h2>
        <p>
          If these terms change, this page will be updated and the &quot;last updated&quot;
          date above will change with it.
        </p>

        <h2>Contact</h2>
        <p>
          Quinai LLC
          <br />
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
        </p>
      </div>
    </main>
  );
}
